import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=process.env.GAME_URL||'http://localhost:4173';
const b=await chromium.launch({channel:'msedge',headless:true});
const p=await b.newPage({viewport:{width:1200,height:630}}),errors=[];
p.on('pageerror',e=>errors.push(e.message));
await p.goto(base+'/?test=1');await p.waitForFunction(()=>window.__batwing?.ready,{},{timeout:60000});
assert.match(await p.title(),/Batman 1989 Game Online/);
assert.equal(await p.locator('link[rel=canonical]').getAttribute('href'),'https://batman1989.co.uk/');
const data=JSON.parse(await p.locator('script[type="application/ld+json"]').textContent());assert.equal(data['@type'],'VideoGame');assert.equal(data.isAccessibleForFree,true);
assert.ok(await p.locator('footer a[href="./about.html"]').isVisible());
if(!process.env.GAME_URL)await p.screenshot({path:'public/social-preview.jpg',type:'jpeg',quality:85});
await p.locator('footer a[href="./about.html"]').click();assert.match(await p.locator('h1').textContent(),/Batman 1989/);
await p.waitForFunction(()=>document.querySelector('img').complete&&document.querySelector('img').naturalWidth===1200);
await p.screenshot({path:'verification/seo-about.png',fullPage:true});
const nojs=await b.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});
await nojs.goto(base+'/about.html');assert.ok(await nojs.locator('h1').isVisible());
assert.equal(await nojs.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await nojs.goto(base+'/');assert.ok(await nojs.locator('noscript a').isVisible());
for(const path of ['/robots.txt','/sitemap.xml','/social-preview.jpg'])assert.equal((await p.request.get(base+path)).status(),200);
assert.match(await (await p.request.get(base+'/robots.txt')).text(),/Sitemap: https:\/\/batman1989.co.uk\/sitemap.xml/);
const xml=await (await p.request.get(base+'/sitemap.xml')).text();assert.equal((xml.match(/<loc>/g)||[]).length,3);
assert.deepEqual(errors,[]);await b.close();console.log('PASS: titles, canonical, JSON-LD, crawlable navigation, share image, no-JS content, mobile overflow, robots and sitemap');
